const staffData = [{
        staffNo: '001',
        name: 'John Doe',
        email: 'john.doe@example.com',
        designation: 'Manager',
        department: 'Sales',
        role: 'Sales Executive',
        netSalary: '$5,000',
        salaryStatus: 'Paid',
    },
    {
        staffNo: '002',
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        designation: 'Developer',
        department: 'Engineering',
        role: 'Software Engineer',
        netSalary: '$4,500',
        salaryStatus: 'Unpaid',
    },
    {
        staffNo: '003',
        name: 'Alice Johnson',
        email: 'alice.johnson@example.com',
        designation: 'Designer',
        department: 'Design',
        role: 'UI/UX Designer',
        netSalary: '$4,200',
        salaryStatus: 'Pending',
    },
    {
        staffNo: '004',
        name: 'Bob Brown',
        email: 'bob.brown@example.com',
        designation: 'Manager',
        department: 'HR',
        role: 'HR Manager',
        netSalary: '$5,200',
        salaryStatus: 'Paid',
    },
    {
        staffNo: '005',
        name: 'John Doe',
        email: 'john.doe@example.com',
        designation: 'Manager',
        department: 'Sales',
        role: 'Sales Executive',
        netSalary: '$5,000',
        salaryStatus: 'Paid',
    },
    {
        staffNo: '006',
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        designation: 'Developer',
        department: 'Engineering',
        role: 'Software Engineer',
        netSalary: '$4,500',
        salaryStatus: 'Unpaid',
    },
    {
        staffNo: '007',
        name: 'Alice Johnson',
        email: 'alice.johnson@example.com',
        designation: 'Designer',
        department: 'Design',
        role: 'UI/UX Designer',
        netSalary: '$4,200',
        salaryStatus: 'Pending',
    },
    {
        staffNo: '008',
        name: 'Bob Brown',
        email: 'bob.brown@example.com',
        designation: 'Manager',
        department: 'HR',
        role: 'HR Manager',
        netSalary: '$5,200',
        salaryStatus: 'Paid',
    },
];

export default staffData;