const designationsData = [
    { id: 1, name: 'Manager' },
    { id: 2, name: 'Software Developer' },
    { id: 3, name: 'Product Manager' },
    { id: 4, name: 'UI/UX Designer' },
    { id: 5, name: 'Data Analyst' },
    { id: 6, name: 'QA Engineer' },
    { id: 7, name: 'DevOps Engineer' },
    { id: 8, name: 'Marketing Specialist' },
    { id: 9, name: 'Sales Representative' },
    { id: 10, name: 'Financial Analyst' },
    { id: 11, name: 'Human Resources Manager' },
    { id: 12, name: 'Customer Support Specialist' },
    { id: 13, name: 'Database Administrator' },
    { id: 14, name: 'Network Engineer' },
    { id: 15, name: 'Project Manager' },
    { id: 16, name: 'Content Writer' },
    { id: 17, name: 'Graphic Designer' },
    { id: 18, name: 'Business Analyst' },
    { id: 19, name: 'Accountant' },
    { id: 20, name: 'System Administrator' },
    { id: 21, name: 'Frontend Developer' },
    { id: 22, name: 'Backend Developer' },
    { id: 23, name: 'UI Designer' },
    { id: 24, name: 'Data Scientist' },
    { id: 25, name: 'Sales Manager' },
    { id: 26, name: 'Financial Controller' },
    { id: 27, name: 'Content Manager' },
    { id: 28, name: 'UX Designer' },
    { id: 29, name: 'HR Specialist' },
    { id: 30, name: 'IT Support Specialist' },
];

export default designationsData;