const rolePermissionData = [{
        staffNo: '001',
        name: 'John Doe',
        role: 'Admin',
        email: 'johndoe@example.com',
        emailStatus: true,
    },
    {
        staffNo: '002',
        name: 'Jane Smith',
        role: 'User',
        email: 'janesmith@example.com',
        emailStatus: false,
    },
    {
        staffNo: '003',
        name: 'Alice Johnson',
        role: 'Editor',
        email: 'alice@example.com',
        emailStatus: true,
    },
    {
        staffNo: '004',
        name: 'Bob Wilson',
        role: 'User',
        email: 'bob@example.com',
        emailStatus: false,
    },
    {
        staffNo: '005',
        name: 'Eva Brown',
        role: 'Admin',
        email: 'eva@example.com',
        emailStatus: true,
    },
    {
        staffNo: '006',
        name: 'Michael Clark',
        role: 'User',
        email: 'michael@example.com',
        emailStatus: false,
    },
    {
        staffNo: '007',
        name: 'Olivia White',
        role: 'Editor',
        email: 'olivia@example.com',
        emailStatus: true,
    },
    {
        staffNo: '008',
        name: 'David Lee',
        role: 'Admin',
        email: 'david@example.com',
        emailStatus: false,
    },
    {
        staffNo: '009',
        name: 'Sophia Adams',
        role: 'User',
        email: 'sophia@example.com',
        emailStatus: true,
    },
    {
        staffNo: '010',
        name: 'Liam Turner',
        role: 'User',
        email: 'liam@example.com',
        emailStatus: false,
    },
    {
        staffNo: '011',
        name: 'Ava Evans',
        role: 'Editor',
        email: 'ava@example.com',
        emailStatus: true,
    },
    {
        staffNo: '012',
        name: 'James Miller',
        role: 'Admin',
        email: 'james@example.com',
        emailStatus: false,
    },
    {
        staffNo: '013',
        name: 'Mia Harris',
        role: 'User',
        email: 'mia@example.com',
        emailStatus: true,
    },
    {
        staffNo: '014',
        name: 'Benjamin Martinez',
        role: 'Editor',
        email: 'benjamin@example.com',
        emailStatus: false,
    },
    {
        staffNo: '015',
        name: 'Emma Thompson',
        role: 'Admin',
        email: 'emma@example.com',
        emailStatus: true,
    },
    {
        staffNo: '016',
        name: 'William Baker',
        role: 'User',
        email: 'william@example.com',
        emailStatus: false,
    },
    {
        staffNo: '017',
        name: 'Sofia Mitchell',
        role: 'User',
        email: 'sofia@example.com',
        emailStatus: true,
    },
    {
        staffNo: '018',
        name: 'Daniel Hall',
        role: 'Editor',
        email: 'daniel@example.com',
        emailStatus: false,
    },
    {
        staffNo: '019',
        name: 'Avery Young',
        role: 'Admin',
        email: 'avery@example.com',
        emailStatus: true,
    },
    {
        staffNo: '020',
        name: 'Oliver Hernandez',
        role: 'User',
        email: 'oliver@example.com',
        emailStatus: false,
    },
    // Add 10 more entries if needed
];

export default rolePermissionData;