const StaffData = [{
        id: 1,
        staffNo: 'S001',
        name: 'John Doe',
        role: 'Manager',
        department: 'HR',
        designation: 'HR Manager',
        email: 'john.doe@example.com',
        status: 'Active',
    },
    {
        id: 2,
        staffNo: 'S002',
        name: 'Jane Smith',
        role: 'Developer',
        department: 'Engineering',
        designation: 'Software Developer',
        email: 'jane.smith@example.com',
        status: 'Active',
    },
    {
        id: 3,
        staffNo: 'S003',
        name: 'Alice Johnson',
        role: 'Designer',
        department: 'Design',
        designation: 'UI/UX Designer',
        email: 'alice.johnson@example.com',
        status: 'Inactive',
    },
    {
        id: 4,
        staffNo: 'S004',
        name: 'Bob Brown',
        role: 'Analyst',
        department: 'Analytics',
        designation: 'Data Analyst',
        email: 'bob.brown@example.com',
        status: 'Active',
    },
    {
        id: 5,
        staffNo: 'S005',
        name: 'Eva Martinez',
        role: 'Engineer',
        department: 'Engineering',
        designation: 'QA Engineer',
        email: 'eva.martinez@example.com',
        status: 'Active',
    },
    // Add more staff objects as needed...
];

export default StaffData;