const dummyData = [{
        sl: 1,
        class: "Class A",
        section: "Section 1",
        subject: "Math",
        lesson: "Addition",
        topic: "Introduction",
    },
    {
        sl: 2,
        class: "Class B",
        section: "Section 2",
        subject: "Science",
        lesson: "Chemistry",
        topic: "Chemical Reactions",
    },
    {
        sl: 3,
        class: "Class C",
        section: "Section 1",
        subject: "English",
        lesson: "Grammar",
        topic: "Verbs",
    },
    {
        sl: 4,
        class: "Class A",
        section: "Section 2",
        subject: "History",
        lesson: "Ancient Civilizations",
        topic: "Egyptian Empire",
    },
    {
        sl: 5,
        class: "Class D",
        section: "Section 1",
        subject: "Geography",
        lesson: "Continents",
        topic: "Africa",
    },
    {
        sl: 6,
        class: "Class B",
        section: "Section 1",
        subject: "Math",
        lesson: "Subtraction",
        topic: "Basics",
    },
    {
        sl: 7,
        class: "Class A",
        section: "Section 3",
        subject: "Science",
        lesson: "Biology",
        topic: "Human Anatomy",
    },
    {
        sl: 8,
        class: "Class C",
        section: "Section 2",
        subject: "English",
        lesson: "Literature",
        topic: "Shakespearean Sonnets",
    },
    {
        sl: 9,
        class: "Class B",
        section: "Section 3",
        subject: "History",
        lesson: "World Wars",
        topic: "WWII",
    },
    {
        sl: 10,
        class: "Class D",
        section: "Section 2",
        subject: "Geography",
        lesson: "Countries",
        topic: "United States",
    },
];
export default dummyData;